DreamIn-Developer/client

- components/initialRegister/button/Button.stories.tsx
- components/initialRegister/button/Button.style.ts
- components/initialRegister/button/Button.tsx
- components/initialRegister/button/Button.type.ts
공통 및 조건부 스타일 적용
#14
<br />
- InitialRegister Button 공통 및 조건부 스타일링
- 각 상황에 맞는 Button 이벤트 기능 구현
<br />
<br />
> ✨ InitialRegister Button

- config.ts
- hooks/useUserInfoInput.ts
- pages/api/base.api.ts
- pages/api/type/index.ts
- pages/api/users.api.ts
<br />
- baseAPI 초기 세팅
<br />
- baseAPI 초기 세팅
- 기존 API 함수를 인스턴스 메서드로 수정
<br />
> Feature/#23 BaseAPI

- tsconfig.json
> fix: 절대경로 수정

- pages/profile.tsx
- pages/team/[id].tsx
> hotfix: deploy

- components/Upload/Register/Register.style.ts
- components/Upload/Register/index.tsx
- components/common/ImageUploadWrapper/index.tsx
- package-lock.json
- package.json
<br />
유저가 작품 업로드를 위해 로컬에서 이미지를 선택하면 <br/>
선택한 이미지를 화면에 미리보기로 렌더링한다.
<br />
FileReader를 통해 미리보기 구현
<br />
> :sparkles: Upload 페이지 이미지 미리보기 구현

- components/initialRegister/SetUserProfile/index.tsx
> ✨ 프로필 이미지 등록 기능 구현

- apis/posts.api.ts
- components/Upload/Editor/Editor.style.ts
- components/Upload/Editor/index.tsx
- components/Upload/Register/Register.style.ts
- components/Upload/Register/index.tsx
- constants/imgUrl.ts
- hooks/useUploadImage.ts
- pages/upload.tsx
- types/post.d.ts
> ✨ 작품 업로드 기능 구현

- apis/users.api.ts
> ✨ 닉네임 중복확인 api 최신화

- apis/posts.api.ts
- apis/users.api.ts
- components/Posts/UserPost/PostArticle/index.tsx
- components/Posts/UserPost/UserPostContent/index.tsx
- components/Posts/UserPost/UserPostHeader/PostHeaderButtons.tsx/index.tsx
- components/Posts/UserPost/UserPostHeader/PostHeaderInfo/index.tsx
- components/Posts/UserPost/UserPostHeader/SkeletonHeader SkeletonHeader.tsx
- components/Posts/UserPost/UserPostHeader/index.tsx
- components/Posts/UserPost/index.tsx
- pages/posts/[id].tsx
- types/post.d.ts
- types/user.d.ts
- utils/isLoggedIn.ts
> ✨ 작품보기 페이지 구현

- apis/teams.api.ts
- apis/users.api.ts
- components/Profile/UploadProduct/index.tsx
- components/Team/Manangement/ManagedMemberCard/index.tsx
- components/Team/Manangement/TeamApplyModal/index.tsx
- components/Team/Manangement/TeamMemberModal/index.tsx
- components/Team/Profile/ApplyTeam/index.tsx
- components/User/Following/index.tsx
- components/User/PostList/index.tsx
- components/common/Thumbnail/index.tsx
- hooks/useUploadImage.ts
- pages/team/[id].tsx
- pages/user/[id].tsx
- types/post.d.ts
- types/team.d.ts
- types/user.d.ts
> ✨ 게시물,팀관리,프로필  api 연동

- components/common/Modal/ModalTemplate/index.tsx
- components/initialRegister/SetUserProfile/SetUserProfile.style.ts
- components/initialRegister/SetUserProfile/index.tsx
- components/initialRegister/userEdit.api.ts
- pages/oauth/_components/SignUpModal.tsx
- types/user.d.ts
<br />
- 최초 프로필 설정 페이지 수정된 디자인 및 레이아웃 적용
<br />
- 이메일 삭제
- 프로필 설정 플로우 수정
- 프로필 설정 완료시 유저 페이지로 이동하게 끔 설정
- useUploadImage훅으로 ImageUploadWrapper 컴포넌트 대체
> ✨ 최초 프로필 설정 페이지 수정된 디자인 및 레이아웃 적용

- components/initialRegister/Button/index.tsx
- pages/oauth/google.tsx
- pages/oauth/kakao.tsx
<br />
- 로그인 시 이전페이지로 이동하도록 수정
<br />
- 로그인 시 이전 페이지가 아닌 메인페이지로 이동하는 문제 해결
- 첫 로그인 시 메인페이지로 이동하여 프로필설정 모달창이 뜨지 않는 문제 해결
<br />
> ✨ 로그인 시 이전페이지로 이동하도록 수정

- components/Login/index.tsx
- hooks/usePathStorage.ts
- pages/oauth/google.tsx
- pages/oauth/kakao.tsx
<br />
- 로그인 시 로그인 이전 페이지로 이동되는 기능 구현
<br />
- 페이지 주소를 저장하고 되돌리는 훅 구현
- 로그인 시 로그인 이전 페이지로 이동되는 기능 구현
<br />
> ✨ 로그인 시 로그인 이전 페이지로 이동되는 기능 구현

- components/header/Header.style.ts
- components/header/index.tsx
- pages/index.tsx
> ✨ 미구현 기능 alert 임시구현

- apis/posts.api.ts
> ✨ getPost타입 리턴값 변경

- apis/posts.api.ts
- components/common/MainCard/index.tsx
- pages/index.tsx
- types/post.d.ts
> ✨ Get Post With Client Data

- components/Profile/AddImage/index.tsx
- components/Profile/PopUp/index.tsx
- components/Team/Profile/MemberList/index.tsx
- pages/team/edit/[id].tsx
- pages/user/edit/[id].tsx
- pages/user/upload.tsx
> 🐛 작품 업로드 유저,팀 분리

- components/Team/Manangement/AcceptApplyButton/index.tsx
- components/Team/Manangement/RejectApplyButton/index.tsx
- components/Team/Manangement/TeamApplyModal/index.tsx
- components/Team/Manangement/TeamMemberModal/index.tsx
- components/Team/Profile/MemberCard/index.tsx
- pages/team/index.tsx
> 🐛 누락된 커밋 추가

- components/common/MainCard/index.tsx
<br />
- getAuthor Data가 캐싱되어 Author가 제대로 반영되지 않는 버그 수정
<br />
- getAuthor의 Query Key를 동적으로 받아오도록 만들어 캐싱되지 않도록 수정함
<br />
> 🐛 getAuthor Data가 캐싱되어 Author가 제대로 반영되지 않는 버그 수정

- components/Profile/AddImage/index.tsx
- components/Team/Manangement/TeamCard/index.tsx
- components/Team/Profile/TeamNickname/index.tsx
- components/Team/Profile/TeamProfileImg/index.tsx
- components/User/NickName/index.tsx
- components/User/ProfileImage/index.tsx
- pages/team/[id].tsx
- pages/user/[id].tsx
- utils/userEditForm.ts
> refact: 컴포넌트 분리

- pages/index.tsx
> 💄 메인페이지 PostCards 정렬 레이아웃 space-around로 변경

- apis/posts.api.ts
- components/common/MainCard/index.tsx
- pages/index.tsx
- types/post.d.ts
> ✨메인페이지에서 팀포스트도 함께 보여줄 수 있도록 구현

- apis/teamPosts.api.ts
- apis/teams.api.ts
- components/Posts/TeamPost/TeamPostContent/index.tsx
- components/Posts/TeamPost/TeamPostHeader/SkeletonHeader SkeletonTeamHeader.tsx
- components/Posts/TeamPost/TeamPostHeader/TeamPostHeaderInfo/index.tsx
- components/Posts/TeamPost/TeamPostHeader/index.tsx
- components/common/MainCard/index.tsx
- pages/post/team/[id].tsx
- types/post.d.ts
> ✨팀포스트 페이지 초안 구현

- pages/index.tsx
> ✨메인 페이지에서 랜덤으로 포스트카드를 섞도록 구현

- README.md
> 📝 리드미 초안 작성

- pages/_app.tsx
> chore: 리액트 쿼리 개발모드분기 설정

- pages/team/[id].tsx
- pages/user/[id].tsx
> fix: 초기 수정 모드 수정

- hooks/useUploadImage.ts
- pages/team/[id].tsx
- pages/user/[id].tsx
> fix: 수정 초기 화면

- pages/user/[id].tsx
> fix: 수정시 카테고리 반영 안되는 현상 수정

- pages/index.tsx
> ✨TempVoidCard를 구현하여 최하단 레이아웃 정렬을 좌측정렬로 구현

- components/header/HeaderProfile/index.tsx
> ✨ 로그아웃 시 메인으로 라우팅

- components/common/MainCard/index.tsx
- pages/index.tsx
- types/post.d.ts
> ✨ 메인페이지에서 여러번 호출되는 쿼리를 통합하도록 수정

- apis/teamPosts.api.ts
- components/Posts/TeamPost/TeamPostHeader/TeamPostHeaderButtons.tsx/index.tsx
- components/Posts/TeamPost/TeamPostHeader/index.tsx
> ✨ 팀포스트 헤더버튼 구현

- README.md
> 📝 리드미 배포링크 및 gif 추가

- components/header/HeaderProfile/index.tsx
> 🐛 로그아웃 후에도 헤더에 로그인 정보가 남아있는 버그 수정

- pages/index.tsx
> 💄 메인페이지 카드 배열 그리드 구현

- components/Team/Manangement/TeamCard/index.tsx
- components/Team/Manangement/TeamCreateModal/index.tsx
- components/common/Thumbnail/index.tsx
> style: 스타일 리뷰 반영

- components/Team/Profile/ApplyTeam/index.tsx
- pages/team/[id].tsx
> fix: 팀 신청중일때, 신청중인지 표시

- components/common/Thumbnail/index.tsx
- types/post.d.ts
> fix: 팀 수정페이지 타입에러 수정

- pages/team/edit/[id].tsx
- pages/user/edit/[id].tsx
> fix: 수정페이지 진입 시, 기존 작품 노출되지 않는 현상 수정
